[package]
name = "drsm"
description = "Dylan's Rusty Stack Machine"
version = "0.15.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
documented = "0.10.0"
indexmap = "2.14.0"
lean_string = "0.7.0"
logos = "0.16.1"
rustyline = "18.0.1"
strum = { version = "0.28.0", features = ["derive"] }
thiserror = "2.0.19"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[dev-dependencies]
chaos_theory = { version = "0.3.5", features = ["derive", "regex"] }
criterion = "0.8.2"

[lib]
bench = false

[[bin]]
name = "drsm"
path = "src/main.rs"
bench = false

[[bench]]
name = "fib"
harness = false

[[bench]]
name = "zero_sum"
harness = false
